// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: example_project

#include "../ui.h"

void ui_PM4graph_screen_init(void)
{
ui_PM4graph = lv_obj_create(NULL);
lv_obj_clear_flag( ui_PM4graph, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PM4graph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PM4graph, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM4chart = lv_chart_create(ui_PM4graph);
lv_obj_set_width( ui_PM4chart, 262);
lv_obj_set_height( ui_PM4chart, 132);
lv_obj_set_x( ui_PM4chart, 13 );
lv_obj_set_y( ui_PM4chart, -9 );
lv_obj_set_align( ui_PM4chart, LV_ALIGN_CENTER );
lv_chart_set_type( ui_PM4chart, LV_CHART_TYPE_BAR);
lv_chart_set_point_count( ui_PM4chart, 15);
lv_chart_set_range( ui_PM4chart, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
lv_chart_set_div_line_count( ui_PM4chart, 0, 0);
lv_chart_set_axis_tick( ui_PM4chart, LV_CHART_AXIS_PRIMARY_X, 0, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_PM4chart, LV_CHART_AXIS_PRIMARY_Y, 5, 5, 11, 2, true, 50);
lv_chart_set_axis_tick( ui_PM4chart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
lv_obj_set_style_bg_color(ui_PM4chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PM4chart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_graphparameter1 = lv_label_create(ui_PM4graph);
lv_obj_set_width( ui_graphparameter1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_graphparameter1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_graphparameter1, -121 );
lv_obj_set_y( ui_graphparameter1, -99 );
lv_obj_set_align( ui_graphparameter1, LV_ALIGN_CENTER );
lv_label_set_text(ui_graphparameter1,"PM4.0");
lv_obj_set_style_text_color(ui_graphparameter1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_graphparameter1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_graphparameter1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container12 = lv_obj_create(ui_PM4graph);
lv_obj_remove_style_all(ui_Container12);
lv_obj_set_width( ui_Container12, 314);
lv_obj_set_height( ui_Container12, 30);
lv_obj_set_x( ui_Container12, 1 );
lv_obj_set_y( ui_Container12, -99 );
lv_obj_set_align( ui_Container12, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container12, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Container12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Container12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gpunit1 = lv_label_create(ui_PM4graph);
lv_obj_set_width( ui_gpunit1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gpunit1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_gpunit1, -76 );
lv_obj_set_y( ui_gpunit1, -98 );
lv_obj_set_align( ui_gpunit1, LV_ALIGN_CENTER );
lv_label_set_text(ui_gpunit1,"ug/m");
lv_obj_set_style_text_color(ui_gpunit1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_gpunit1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_gpunit1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pm4cv = lv_label_create(ui_PM4graph);
lv_obj_set_width( ui_pm4cv, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pm4cv, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pm4cv, 99 );
lv_obj_set_y( ui_pm4cv, -100 );
lv_obj_set_align( ui_pm4cv, LV_ALIGN_CENTER );
lv_label_set_text(ui_pm4cv,"1400");
lv_obj_set_style_text_color(ui_pm4cv, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_pm4cv, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pm4cv, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_return1 = lv_btn_create(ui_PM4graph);
lv_obj_set_width( ui_return1, 245);
lv_obj_set_height( ui_return1, 37);
lv_obj_set_x( ui_return1, 9 );
lv_obj_set_y( ui_return1, 85 );
lv_obj_set_align( ui_return1, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_return1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_return1, lv_color_hex(0x086100), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_return1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_return1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_return1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_returnlabel1 = lv_label_create(ui_PM4graph);
lv_obj_set_width( ui_returnlabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_returnlabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_returnlabel1, 6 );
lv_obj_set_y( ui_returnlabel1, 86 );
lv_obj_set_align( ui_returnlabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_returnlabel1,"RETURN");
lv_obj_set_style_text_color(ui_returnlabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_returnlabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_returnlabel1, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cube2 = lv_label_create(ui_PM4graph);
lv_obj_set_width( ui_cube2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cube2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_cube2, -59 );
lv_obj_set_y( ui_cube2, -104 );
lv_obj_set_align( ui_cube2, LV_ALIGN_CENTER );
lv_label_set_text(ui_cube2,"3");
lv_obj_set_style_text_color(ui_cube2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_cube2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_cube2, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_return1, ui_event_return1, LV_EVENT_ALL, NULL);

}
