// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: example_project

#include "../ui.h"

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart4 = lv_chart_create(ui_Screen7);
    lv_obj_set_width(ui_Chart4, 262);
    lv_obj_set_height(ui_Chart4, 132);
    lv_obj_set_x(ui_Chart4, 13);
    lv_obj_set_y(ui_Chart4, -9);
    lv_obj_set_align(ui_Chart4, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart4, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart4, 15);
    lv_chart_set_range(ui_Chart4, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_Chart4, 0, 0);
    lv_chart_set_axis_tick(ui_Chart4, LV_CHART_AXIS_PRIMARY_X, 0, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_Chart4, LV_CHART_AXIS_PRIMARY_Y, 5, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart4, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_Chart4_series_1 = lv_chart_add_series(ui_Chart4, lv_color_hex(0x086003),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart4_series_1_array[] = { 550, 650, 750, 800, 1500, 1200, 1110, 800, 800, 1200, 1400, 1700, 1300, 1100, 600 };
    lv_chart_set_ext_y_array(ui_Chart4, ui_Chart4_series_1, ui_Chart4_series_1_array);
    lv_obj_set_style_bg_color(ui_Chart4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_graphparameter3 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_graphparameter3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter3, -121);
    lv_obj_set_y(ui_graphparameter3, -99);
    lv_obj_set_align(ui_graphparameter3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter3, "PM10.0");
    lv_obj_set_style_text_color(ui_graphparameter3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_Screen7);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 314);
    lv_obj_set_height(ui_Container15, 30);
    lv_obj_set_x(ui_Container15, 1);
    lv_obj_set_y(ui_Container15, -99);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container15, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpunit3 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_gpunit3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpunit3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpunit3, -76);
    lv_obj_set_y(ui_gpunit3, -98);
    lv_obj_set_align(ui_gpunit3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpunit3, "ug/m");
    lv_obj_set_style_text_color(ui_gpunit3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpunit3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpunit3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpvalue3 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_gpvalue3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpvalue3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpvalue3, 99);
    lv_obj_set_y(ui_gpvalue3, -100);
    lv_obj_set_align(ui_gpvalue3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpvalue3, "1136");
    lv_obj_set_style_text_color(ui_gpvalue3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpvalue3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpvalue3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return3 = lv_btn_create(ui_Screen7);
    lv_obj_set_width(ui_return3, 245);
    lv_obj_set_height(ui_return3, 37);
    lv_obj_set_x(ui_return3, 9);
    lv_obj_set_y(ui_return3, 85);
    lv_obj_set_align(ui_return3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_return3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_return3, lv_color_hex(0x086100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_return3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_return3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnlabel3 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_returnlabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_returnlabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_returnlabel3, 6);
    lv_obj_set_y(ui_returnlabel3, 86);
    lv_obj_set_align(ui_returnlabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_returnlabel3, "RETURN");
    lv_obj_set_style_text_color(ui_returnlabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_returnlabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_returnlabel3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_return3, ui_event_return3, LV_EVENT_ALL, NULL);

}
