// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: example_project

#include "../ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart2 = lv_chart_create(ui_Screen6);
    lv_obj_set_width(ui_Chart2, 262);
    lv_obj_set_height(ui_Chart2, 132);
    lv_obj_set_x(ui_Chart2, 13);
    lv_obj_set_y(ui_Chart2, -9);
    lv_obj_set_align(ui_Chart2, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart2, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_Chart2, 15);
    lv_chart_set_range(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
    lv_chart_set_div_line_count(ui_Chart2, 0, 0);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_X, 0, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_PRIMARY_Y, 5, 5, 11, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart2, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
    lv_chart_series_t * ui_Chart2_series_1 = lv_chart_add_series(ui_Chart2, lv_color_hex(0x086003),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart2_series_1_array[] = { 550, 650, 750, 800, 1500, 1200, 1110, 800, 800, 1200, 1400, 1700, 1300, 1100, 600 };
    lv_chart_set_ext_y_array(ui_Chart2, ui_Chart2_series_1, ui_Chart2_series_1_array);
    lv_obj_set_style_bg_color(ui_Chart2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_graphparameter2 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_graphparameter2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_graphparameter2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_graphparameter2, -121);
    lv_obj_set_y(ui_graphparameter2, -99);
    lv_obj_set_align(ui_graphparameter2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_graphparameter2, "PM2.5");
    lv_obj_set_style_text_color(ui_graphparameter2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_graphparameter2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_graphparameter2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_Screen6);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 314);
    lv_obj_set_height(ui_Container14, 30);
    lv_obj_set_x(ui_Container14, 1);
    lv_obj_set_y(ui_Container14, -99);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Container14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Container14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Container14, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Container14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Container14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpunit2 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_gpunit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpunit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpunit2, -76);
    lv_obj_set_y(ui_gpunit2, -98);
    lv_obj_set_align(ui_gpunit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpunit2, "ug/m");
    lv_obj_set_style_text_color(ui_gpunit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpunit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpunit2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gpvalue2 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_gpvalue2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gpvalue2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gpvalue2, 99);
    lv_obj_set_y(ui_gpvalue2, -100);
    lv_obj_set_align(ui_gpvalue2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gpvalue2, "1600");
    lv_obj_set_style_text_color(ui_gpvalue2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_gpvalue2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_gpvalue2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_return2 = lv_btn_create(ui_Screen6);
    lv_obj_set_width(ui_return2, 245);
    lv_obj_set_height(ui_return2, 37);
    lv_obj_set_x(ui_return2, 9);
    lv_obj_set_y(ui_return2, 85);
    lv_obj_set_align(ui_return2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_return2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_return2, lv_color_hex(0x086100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_return2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_return2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_return2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnlabel2 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_returnlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_returnlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_returnlabel2, 6);
    lv_obj_set_y(ui_returnlabel2, 86);
    lv_obj_set_align(ui_returnlabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_returnlabel2, "RETURN");
    lv_obj_set_style_text_color(ui_returnlabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_returnlabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_returnlabel2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_return2, ui_event_return2, LV_EVENT_ALL, NULL);

}
