#include <Arduino.h>
#if defined(ARDUINO_M5STACK_Core2)
#include <M5Core2.h>
#endif
#if defined(ARDUINO_M5STACK_CORES3)
// #include <M5CoreS3.h>  // no touch support yet
#include <M5Unified.h>
#endif
#include <FS.h>

#include "time_func.h"
#include "pm1.h"
#include "ui/lv_setup.h"
#include "ui/ui.h"




void setup() {
  M5.begin();  // Initialize the M5Stack peripherals
  lv_begin();  // Initialize LVGL for the Core2 screen
  ui_init();   // Initialize UI generated by Square Line
  time_init(); // Initialize time and date from compiler
  //update_chart_array();

}

void loop() {  
  lv_handler();  // Update UI
  update_time(); // Update time and date on UI 
  pm1func(); // to update value of pm1

  
}