// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: example_project

#include "../ui.h"

void ui_dashboard_screen_init(void)
{
ui_dashboard = lv_obj_create(NULL);
lv_obj_clear_flag( ui_dashboard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_dashboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_dashboard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container6 = lv_obj_create(ui_dashboard);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, 314);
lv_obj_set_height( ui_Container6, 30);
lv_obj_set_x( ui_Container6, 0 );
lv_obj_set_y( ui_Container6, -105 );
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container6, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Container6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Container6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container7 = lv_obj_create(ui_dashboard);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, 157);
lv_obj_set_height( ui_Container7, 83);
lv_obj_set_x( ui_Container7, -79 );
lv_obj_set_y( ui_Container7, -49 );
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container7, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_Container7);
lv_obj_set_width( ui_Button1, lv_pct(98));
lv_obj_set_height( ui_Button1, lv_pct(100));
lv_obj_set_y( ui_Button1, 0 );
lv_obj_set_x( ui_Button1, lv_pct(1) );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Button1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Button1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pm1label = lv_label_create(ui_Container7);
lv_obj_set_width( ui_pm1label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pm1label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pm1label, -21 );
lv_obj_set_y( ui_pm1label, 12 );
lv_obj_set_align( ui_pm1label, LV_ALIGN_CENTER );
lv_label_set_text(ui_pm1label,"1200");
lv_obj_set_style_text_color(ui_pm1label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_pm1label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pm1label, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container8 = lv_obj_create(ui_dashboard);
lv_obj_remove_style_all(ui_Container8);
lv_obj_set_width( ui_Container8, 157);
lv_obj_set_height( ui_Container8, 85);
lv_obj_set_x( ui_Container8, -79 );
lv_obj_set_y( ui_Container8, 35 );
lv_obj_set_align( ui_Container8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container8, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_btn_create(ui_Container8);
lv_obj_set_width( ui_Button3, lv_pct(98));
lv_obj_set_height( ui_Button3, lv_pct(100));
lv_obj_set_y( ui_Button3, 0 );
lv_obj_set_x( ui_Button3, lv_pct(1) );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Button3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Button3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM3 = lv_label_create(ui_Container8);
lv_obj_set_width( ui_PM3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PM3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PM3, -36 );
lv_obj_set_y( ui_PM3, -18 );
lv_obj_set_align( ui_PM3, LV_ALIGN_CENTER );
lv_label_set_text(ui_PM3,"PM2.5");
lv_obj_set_style_text_color(ui_PM3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PM3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PM3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM1u2 = lv_label_create(ui_Container8);
lv_obj_set_width( ui_PM1u2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PM1u2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PM1u2, 31 );
lv_obj_set_y( ui_PM1u2, -18 );
lv_obj_set_align( ui_PM1u2, LV_ALIGN_CENTER );
lv_label_set_text(ui_PM1u2,"ug/m");
lv_obj_set_style_text_color(ui_PM1u2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PM1u2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PM1u2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM1t2 = lv_label_create(ui_Container8);
lv_obj_set_width( ui_PM1t2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PM1t2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PM1t2, 57 );
lv_obj_set_y( ui_PM1t2, -27 );
lv_obj_set_align( ui_PM1t2, LV_ALIGN_CENTER );
lv_label_set_text(ui_PM1t2,"3");
lv_obj_set_style_text_color(ui_PM1t2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PM1t2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PM1t2, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pm25label = lv_label_create(ui_Container8);
lv_obj_set_width( ui_pm25label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pm25label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pm25label, -23 );
lv_obj_set_y( ui_pm25label, 16 );
lv_obj_set_align( ui_pm25label, LV_ALIGN_CENTER );
lv_label_set_text(ui_pm25label,"1600");
lv_obj_set_style_text_color(ui_pm25label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_pm25label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pm25label, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM1 = lv_label_create(ui_dashboard);
lv_obj_set_width( ui_PM1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PM1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PM1, -118 );
lv_obj_set_y( ui_PM1, -73 );
lv_obj_set_align( ui_PM1, LV_ALIGN_CENTER );
lv_label_set_text(ui_PM1,"PM1.0");
lv_obj_set_style_text_color(ui_PM1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PM1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PM1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM1u = lv_label_create(ui_dashboard);
lv_obj_set_width( ui_PM1u, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PM1u, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PM1u, -55 );
lv_obj_set_y( ui_PM1u, -72 );
lv_obj_set_align( ui_PM1u, LV_ALIGN_CENTER );
lv_label_set_text(ui_PM1u,"ug/m");
lv_obj_set_style_text_color(ui_PM1u, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PM1u, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PM1u, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM1t = lv_label_create(ui_dashboard);
lv_obj_set_width( ui_PM1t, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PM1t, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PM1t, -28 );
lv_obj_set_y( ui_PM1t, -76 );
lv_obj_set_align( ui_PM1t, LV_ALIGN_CENTER );
lv_label_set_text(ui_PM1t,"3");
lv_obj_set_style_text_color(ui_PM1t, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PM1t, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PM1t, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RHpercent = lv_label_create(ui_dashboard);
lv_obj_set_width( ui_RHpercent, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RHpercent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RHpercent, 130 );
lv_obj_set_y( ui_RHpercent, -106 );
lv_obj_set_align( ui_RHpercent, LV_ALIGN_CENTER );
lv_label_set_text(ui_RHpercent,"RH%");
lv_obj_set_style_text_color(ui_RHpercent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RHpercent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RHpercent, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TVOC = lv_label_create(ui_dashboard);
lv_obj_set_width( ui_TVOC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TVOC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TVOC, -117 );
lv_obj_set_y( ui_TVOC, 97 );
lv_obj_set_align( ui_TVOC, LV_ALIGN_CENTER );
lv_label_set_text(ui_TVOC,"TVOC");
lv_obj_set_style_text_color(ui_TVOC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TVOC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TVOC, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TVOC, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TVOC, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TVOCppb = lv_label_create(ui_dashboard);
lv_obj_set_width( ui_TVOCppb, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TVOCppb, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TVOCppb, -57 );
lv_obj_set_y( ui_TVOCppb, 98 );
lv_obj_set_align( ui_TVOCppb, LV_ALIGN_CENTER );
lv_label_set_text(ui_TVOCppb,"ppb");
lv_obj_set_style_text_color(ui_TVOCppb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TVOCppb, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TVOCppb, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container9 = lv_obj_create(ui_dashboard);
lv_obj_remove_style_all(ui_Container9);
lv_obj_set_width( ui_Container9, 157);
lv_obj_set_height( ui_Container9, 83);
lv_obj_set_x( ui_Container9, 78 );
lv_obj_set_y( ui_Container9, -49 );
lv_obj_set_align( ui_Container9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container9, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_btn_create(ui_Container9);
lv_obj_set_width( ui_Button2, lv_pct(91));
lv_obj_set_height( ui_Button2, lv_pct(100));
lv_obj_set_y( ui_Button2, 2 );
lv_obj_set_x( ui_Button2, lv_pct(0) );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Button2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Button2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM4 = lv_label_create(ui_Container9);
lv_obj_set_width( ui_PM4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PM4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PM4, -34 );
lv_obj_set_y( ui_PM4, -22 );
lv_obj_set_align( ui_PM4, LV_ALIGN_CENTER );
lv_label_set_text(ui_PM4,"PM4.0");
lv_obj_set_style_text_color(ui_PM4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PM4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PM4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM1u3 = lv_label_create(ui_Container9);
lv_obj_set_width( ui_PM1u3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PM1u3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PM1u3, 32 );
lv_obj_set_y( ui_PM1u3, -22 );
lv_obj_set_align( ui_PM1u3, LV_ALIGN_CENTER );
lv_label_set_text(ui_PM1u3,"ug/m");
lv_obj_set_style_text_color(ui_PM1u3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PM1u3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PM1u3, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM1t3 = lv_label_create(ui_Container9);
lv_obj_set_width( ui_PM1t3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PM1t3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PM1t3, 57 );
lv_obj_set_y( ui_PM1t3, -31 );
lv_obj_set_align( ui_PM1t3, LV_ALIGN_CENTER );
lv_label_set_text(ui_PM1t3,"3");
lv_obj_set_style_text_color(ui_PM1t3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PM1t3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PM1t3, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pm4label = lv_label_create(ui_Container9);
lv_obj_set_width( ui_pm4label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pm4label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pm4label, -21 );
lv_obj_set_y( ui_pm4label, 12 );
lv_obj_set_align( ui_pm4label, LV_ALIGN_CENTER );
lv_label_set_text(ui_pm4label,"1400");
lv_obj_set_style_text_color(ui_pm4label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_pm4label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pm4label, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container10 = lv_obj_create(ui_dashboard);
lv_obj_remove_style_all(ui_Container10);
lv_obj_set_width( ui_Container10, 156);
lv_obj_set_height( ui_Container10, 85);
lv_obj_set_x( ui_Container10, 79 );
lv_obj_set_y( ui_Container10, 35 );
lv_obj_set_align( ui_Container10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container10, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button4 = lv_btn_create(ui_Container10);
lv_obj_set_width( ui_Button4, lv_pct(98));
lv_obj_set_height( ui_Button4, lv_pct(100));
lv_obj_set_y( ui_Button4, 0 );
lv_obj_set_x( ui_Button4, lv_pct(-2) );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Button4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Button4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM2 = lv_label_create(ui_Container10);
lv_obj_set_width( ui_PM2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PM2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PM2, -31 );
lv_obj_set_y( ui_PM2, -18 );
lv_obj_set_align( ui_PM2, LV_ALIGN_CENTER );
lv_label_set_text(ui_PM2,"PM10.0");
lv_obj_set_style_text_color(ui_PM2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PM2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PM2, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM1u4 = lv_label_create(ui_Container10);
lv_obj_set_width( ui_PM1u4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PM1u4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PM1u4, 38 );
lv_obj_set_y( ui_PM1u4, -20 );
lv_obj_set_align( ui_PM1u4, LV_ALIGN_CENTER );
lv_label_set_text(ui_PM1u4,"ug/m");
lv_obj_set_style_text_color(ui_PM1u4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PM1u4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PM1u4, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM1t4 = lv_label_create(ui_Container10);
lv_obj_set_width( ui_PM1t4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PM1t4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PM1t4, 62 );
lv_obj_set_y( ui_PM1t4, -29 );
lv_obj_set_align( ui_PM1t4, LV_ALIGN_CENTER );
lv_label_set_text(ui_PM1t4,"3");
lv_obj_set_style_text_color(ui_PM1t4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_PM1t4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_PM1t4, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pm10label = lv_label_create(ui_Container10);
lv_obj_set_width( ui_pm10label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pm10label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pm10label, -26 );
lv_obj_set_y( ui_pm10label, 14 );
lv_obj_set_align( ui_pm10label, LV_ALIGN_CENTER );
lv_label_set_text(ui_pm10label,"1136");
lv_obj_set_style_text_color(ui_pm10label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_pm10label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pm10label, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container11 = lv_obj_create(ui_dashboard);
lv_obj_remove_style_all(ui_Container11);
lv_obj_set_width( ui_Container11, 307);
lv_obj_set_height( ui_Container11, 35);
lv_obj_set_x( ui_Container11, -1 );
lv_obj_set_y( ui_Container11, 96 );
lv_obj_set_align( ui_Container11, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container11, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Container11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button6 = lv_btn_create(ui_Container11);
lv_obj_set_width( ui_Button6, lv_pct(98));
lv_obj_set_height( ui_Button6, lv_pct(100));
lv_obj_set_y( ui_Button6, 0 );
lv_obj_set_x( ui_Button6, lv_pct(-2) );
lv_obj_set_align( ui_Button6, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Button6, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Button6, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tvoclabel = lv_label_create(ui_dashboard);
lv_obj_set_width( ui_tvoclabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tvoclabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tvoclabel, 71 );
lv_obj_set_y( ui_tvoclabel, 99 );
lv_obj_set_align( ui_tvoclabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_tvoclabel,"1465");
lv_obj_set_style_text_color(ui_tvoclabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tvoclabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tvoclabel, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_clock2 = lv_label_create(ui_dashboard);
lv_obj_set_width( ui_clock2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clock2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_clock2, 2 );
lv_obj_set_y( ui_clock2, -105 );
lv_obj_set_align( ui_clock2, LV_ALIGN_CENTER );
lv_label_set_text(ui_clock2,"12:25:45");
lv_obj_set_style_text_color(ui_clock2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_clock2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_clock2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_dashboard);
lv_img_set_src(ui_Image3, &ui_img_582762761);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image3, -91 );
lv_obj_set_y( ui_Image3, -105 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image3,170);

ui_templabel = lv_label_create(ui_dashboard);
lv_obj_set_width( ui_templabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_templabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_templabel, -129 );
lv_obj_set_y( ui_templabel, -106 );
lv_obj_set_align( ui_templabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_templabel,"26.5");
lv_obj_set_style_text_color(ui_templabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_templabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_templabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RHlabel = lv_label_create(ui_dashboard);
lv_obj_set_width( ui_RHlabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RHlabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RHlabel, 89 );
lv_obj_set_y( ui_RHlabel, -105 );
lv_obj_set_align( ui_RHlabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_RHlabel,"58");
lv_obj_set_style_text_color(ui_RHlabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RHlabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RHlabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_dashboard);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 314);
lv_obj_set_height( ui_Container1, 39);
lv_obj_set_x( ui_Container1, 0 );
lv_obj_set_y( ui_Container1, 96 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Container1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Container7, ui_event_Container7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Container9, ui_event_Container9, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Container11, ui_event_Container11, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_dashboard, ui_event_dashboard, LV_EVENT_ALL, NULL);

}
