// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: example_project

#include "../ui.h"

void ui_Intro_screen_init(void)
{
ui_Intro = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Intro, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Intro, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Intro, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_logo = lv_imgbtn_create(ui_Intro);
lv_imgbtn_set_src(ui_logo, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_oizom_logo_png, NULL);
lv_imgbtn_set_src(ui_logo, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_oizom_logo_png, NULL);
lv_imgbtn_set_src(ui_logo, LV_IMGBTN_STATE_DISABLED, NULL, &ui__temporary_image, NULL);
lv_imgbtn_set_src(ui_logo, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui__temporary_image, NULL);
lv_imgbtn_set_src(ui_logo, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui__temporary_image, NULL);
lv_imgbtn_set_src(ui_logo, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui__temporary_image, NULL);
lv_obj_set_height( ui_logo, 206);
lv_obj_set_width( ui_logo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_logo, 0 );
lv_obj_set_y( ui_logo, -10 );
lv_obj_set_align( ui_logo, LV_ALIGN_CENTER );

ui_devicename = lv_label_create(ui_Intro);
lv_obj_set_width( ui_devicename, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_devicename, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_devicename, 0 );
lv_obj_set_y( ui_devicename, 99 );
lv_obj_set_align( ui_devicename, LV_ALIGN_CENTER );
lv_label_set_text(ui_devicename,"OIZOM AIROWL");
lv_obj_set_style_text_font(ui_devicename, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_firmwareversion = lv_label_create(ui_Intro);
lv_obj_set_width( ui_firmwareversion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_firmwareversion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_firmwareversion, 0 );
lv_obj_set_y( ui_firmwareversion, -102 );
lv_obj_set_align( ui_firmwareversion, LV_ALIGN_CENTER );
lv_label_set_text(ui_firmwareversion,"version - 1.0");
lv_obj_set_style_text_font(ui_firmwareversion, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_logo, ui_event_logo, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Intro, ui_event_Intro, LV_EVENT_ALL, NULL);

}
