// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: example_project

#include "../ui.h"

void ui_PM25graph_screen_init(void)
{
ui_PM25graph = lv_obj_create(NULL);
lv_obj_clear_flag( ui_PM25graph, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PM25graph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PM25graph, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PM25chart = lv_chart_create(ui_PM25graph);
lv_obj_set_width( ui_PM25chart, 262);
lv_obj_set_height( ui_PM25chart, 132);
lv_obj_set_x( ui_PM25chart, 13 );
lv_obj_set_y( ui_PM25chart, -9 );
lv_obj_set_align( ui_PM25chart, LV_ALIGN_CENTER );
lv_chart_set_type( ui_PM25chart, LV_CHART_TYPE_BAR);
lv_chart_set_point_count( ui_PM25chart, 15);
lv_chart_set_range( ui_PM25chart, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
lv_chart_set_div_line_count( ui_PM25chart, 0, 0);
lv_chart_set_axis_tick( ui_PM25chart, LV_CHART_AXIS_PRIMARY_X, 0, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_PM25chart, LV_CHART_AXIS_PRIMARY_Y, 5, 5, 11, 2, true, 50);
lv_chart_set_axis_tick( ui_PM25chart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
lv_obj_set_style_bg_color(ui_PM25chart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PM25chart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_graphparameter2 = lv_label_create(ui_PM25graph);
lv_obj_set_width( ui_graphparameter2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_graphparameter2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_graphparameter2, -121 );
lv_obj_set_y( ui_graphparameter2, -99 );
lv_obj_set_align( ui_graphparameter2, LV_ALIGN_CENTER );
lv_label_set_text(ui_graphparameter2,"PM2.5");
lv_obj_set_style_text_color(ui_graphparameter2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_graphparameter2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_graphparameter2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container14 = lv_obj_create(ui_PM25graph);
lv_obj_remove_style_all(ui_Container14);
lv_obj_set_width( ui_Container14, 314);
lv_obj_set_height( ui_Container14, 30);
lv_obj_set_x( ui_Container14, 1 );
lv_obj_set_y( ui_Container14, -99 );
lv_obj_set_align( ui_Container14, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container14, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Container14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Container14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gpunit2 = lv_label_create(ui_PM25graph);
lv_obj_set_width( ui_gpunit2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gpunit2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_gpunit2, -76 );
lv_obj_set_y( ui_gpunit2, -98 );
lv_obj_set_align( ui_gpunit2, LV_ALIGN_CENTER );
lv_label_set_text(ui_gpunit2,"ug/m");
lv_obj_set_style_text_color(ui_gpunit2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_gpunit2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_gpunit2, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_return2 = lv_btn_create(ui_PM25graph);
lv_obj_set_width( ui_return2, 245);
lv_obj_set_height( ui_return2, 37);
lv_obj_set_x( ui_return2, 9 );
lv_obj_set_y( ui_return2, 85 );
lv_obj_set_align( ui_return2, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_return2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_return2, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_return2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_return2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_return2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_returnlabel2 = lv_label_create(ui_PM25graph);
lv_obj_set_width( ui_returnlabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_returnlabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_returnlabel2, 6 );
lv_obj_set_y( ui_returnlabel2, 86 );
lv_obj_set_align( ui_returnlabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_returnlabel2,"RETURN");
lv_obj_set_style_text_color(ui_returnlabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_returnlabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_returnlabel2, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_cube4 = lv_label_create(ui_PM25graph);
lv_obj_set_width( ui_cube4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_cube4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_cube4, -59 );
lv_obj_set_y( ui_cube4, -104 );
lv_obj_set_align( ui_cube4, LV_ALIGN_CENTER );
lv_label_set_text(ui_cube4,"3");
lv_obj_set_style_text_color(ui_cube4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_cube4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_cube4, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_graphparameter10 = lv_label_create(ui_PM25graph);
lv_obj_set_width( ui_graphparameter10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_graphparameter10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_graphparameter10, -17 );
lv_obj_set_y( ui_graphparameter10, -97 );
lv_obj_set_align( ui_graphparameter10, LV_ALIGN_CENTER );
lv_label_set_text(ui_graphparameter10,"avg");
lv_obj_set_style_text_color(ui_graphparameter10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_graphparameter10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_graphparameter10, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_graphparameter13 = lv_label_create(ui_PM25graph);
lv_obj_set_width( ui_graphparameter13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_graphparameter13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_graphparameter13, 77 );
lv_obj_set_y( ui_graphparameter13, -96 );
lv_obj_set_align( ui_graphparameter13, LV_ALIGN_CENTER );
lv_label_set_text(ui_graphparameter13,"max");
lv_obj_set_style_text_color(ui_graphparameter13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_graphparameter13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_graphparameter13, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pm25avg = lv_label_create(ui_PM25graph);
lv_obj_set_width( ui_pm25avg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pm25avg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pm25avg, 18 );
lv_obj_set_y( ui_pm25avg, -98 );
lv_obj_set_align( ui_pm25avg, LV_ALIGN_CENTER );
lv_label_set_text(ui_pm25avg,"-");
lv_obj_set_style_text_color(ui_pm25avg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_pm25avg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pm25avg, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pm25max = lv_label_create(ui_PM25graph);
lv_obj_set_width( ui_pm25max, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pm25max, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pm25max, 116 );
lv_obj_set_y( ui_pm25max, -98 );
lv_obj_set_align( ui_pm25max, LV_ALIGN_CENTER );
lv_label_set_text(ui_pm25max,"-");
lv_obj_set_style_text_color(ui_pm25max, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_pm25max, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pm25max, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_return2, ui_event_return2, LV_EVENT_ALL, NULL);

}
