// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: example_project

#include "../ui.h"

void ui_TVOCgraph_screen_init(void)
{
ui_TVOCgraph = lv_obj_create(NULL);
lv_obj_clear_flag( ui_TVOCgraph, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_TVOCgraph, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TVOCgraph, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TVOCchart = lv_chart_create(ui_TVOCgraph);
lv_obj_set_width( ui_TVOCchart, 262);
lv_obj_set_height( ui_TVOCchart, 132);
lv_obj_set_x( ui_TVOCchart, 13 );
lv_obj_set_y( ui_TVOCchart, -9 );
lv_obj_set_align( ui_TVOCchart, LV_ALIGN_CENTER );
lv_chart_set_type( ui_TVOCchart, LV_CHART_TYPE_BAR);
lv_chart_set_point_count( ui_TVOCchart, 15);
lv_chart_set_range( ui_TVOCchart, LV_CHART_AXIS_PRIMARY_Y, 500, 1800);
lv_chart_set_div_line_count( ui_TVOCchart, 0, 0);
lv_chart_set_axis_tick( ui_TVOCchart, LV_CHART_AXIS_PRIMARY_X, 0, 5, 5, 2, false, 50);
lv_chart_set_axis_tick( ui_TVOCchart, LV_CHART_AXIS_PRIMARY_Y, 5, 5, 11, 2, true, 50);
lv_chart_set_axis_tick( ui_TVOCchart, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
lv_obj_set_style_bg_color(ui_TVOCchart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TVOCchart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_graphparameter4 = lv_label_create(ui_TVOCgraph);
lv_obj_set_width( ui_graphparameter4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_graphparameter4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_graphparameter4, -121 );
lv_obj_set_y( ui_graphparameter4, -99 );
lv_obj_set_align( ui_graphparameter4, LV_ALIGN_CENTER );
lv_label_set_text(ui_graphparameter4,"TVOC");
lv_obj_set_style_text_color(ui_graphparameter4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_graphparameter4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_graphparameter4, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container16 = lv_obj_create(ui_TVOCgraph);
lv_obj_remove_style_all(ui_Container16);
lv_obj_set_width( ui_Container16, 314);
lv_obj_set_height( ui_Container16, 30);
lv_obj_set_x( ui_Container16, 1 );
lv_obj_set_y( ui_Container16, -99 );
lv_obj_set_align( ui_Container16, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container16, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Container16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Container16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gpunit4 = lv_label_create(ui_TVOCgraph);
lv_obj_set_width( ui_gpunit4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gpunit4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_gpunit4, -81 );
lv_obj_set_y( ui_gpunit4, -97 );
lv_obj_set_align( ui_gpunit4, LV_ALIGN_CENTER );
lv_label_set_text(ui_gpunit4,"ppb");
lv_obj_set_style_text_color(ui_gpunit4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_gpunit4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_gpunit4, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_return4 = lv_btn_create(ui_TVOCgraph);
lv_obj_set_width( ui_return4, 245);
lv_obj_set_height( ui_return4, 37);
lv_obj_set_x( ui_return4, 9 );
lv_obj_set_y( ui_return4, 85 );
lv_obj_set_align( ui_return4, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_return4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_return4, lv_color_hex(0x41B4D1), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_return4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_return4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_return4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_returnlabel4 = lv_label_create(ui_TVOCgraph);
lv_obj_set_width( ui_returnlabel4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_returnlabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_returnlabel4, 6 );
lv_obj_set_y( ui_returnlabel4, 86 );
lv_obj_set_align( ui_returnlabel4, LV_ALIGN_CENTER );
lv_label_set_text(ui_returnlabel4,"RETURN");
lv_obj_set_style_text_color(ui_returnlabel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_returnlabel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_returnlabel4, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_graphparameter12 = lv_label_create(ui_TVOCgraph);
lv_obj_set_width( ui_graphparameter12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_graphparameter12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_graphparameter12, -17 );
lv_obj_set_y( ui_graphparameter12, -97 );
lv_obj_set_align( ui_graphparameter12, LV_ALIGN_CENTER );
lv_label_set_text(ui_graphparameter12,"avg");
lv_obj_set_style_text_color(ui_graphparameter12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_graphparameter12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_graphparameter12, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_graphparameter15 = lv_label_create(ui_TVOCgraph);
lv_obj_set_width( ui_graphparameter15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_graphparameter15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_graphparameter15, 77 );
lv_obj_set_y( ui_graphparameter15, -96 );
lv_obj_set_align( ui_graphparameter15, LV_ALIGN_CENTER );
lv_label_set_text(ui_graphparameter15,"max");
lv_obj_set_style_text_color(ui_graphparameter15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_graphparameter15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_graphparameter15, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tvocavg = lv_label_create(ui_TVOCgraph);
lv_obj_set_width( ui_tvocavg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tvocavg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tvocavg, 18 );
lv_obj_set_y( ui_tvocavg, -98 );
lv_obj_set_align( ui_tvocavg, LV_ALIGN_CENTER );
lv_label_set_text(ui_tvocavg,"-");
lv_obj_set_style_text_color(ui_tvocavg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tvocavg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tvocavg, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_tvocmax = lv_label_create(ui_TVOCgraph);
lv_obj_set_width( ui_tvocmax, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_tvocmax, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_tvocmax, 116 );
lv_obj_set_y( ui_tvocmax, -98 );
lv_obj_set_align( ui_tvocmax, LV_ALIGN_CENTER );
lv_label_set_text(ui_tvocmax,"-");
lv_obj_set_style_text_color(ui_tvocmax, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_tvocmax, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_tvocmax, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_return4, ui_event_return4, LV_EVENT_ALL, NULL);

}
