// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: example_project

#ifndef _EXAMPLE_PROJECT_UI_H
#define _EXAMPLE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_clock;
extern lv_obj_t *ui_date;
void ui_event_logo( lv_event_t * e);
extern lv_obj_t *ui_logo;
extern lv_obj_t *ui_demo;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui__temporary_image );
LV_IMG_DECLARE( ui_img_sls_logo_png);   // assets/sls_logo.png


LV_FONT_DECLARE( ui_font_clock_66);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
