// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: example_project

#ifndef _EXAMPLE_PROJECT_UI_H
#define _EXAMPLE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void blink_Animation(lv_obj_t * TargetObject, int delay);
void open_Animation(lv_obj_t * TargetObject, int delay);
void blinkx_Animation(lv_obj_t * TargetObject, int delay);
void openx_Animation(lv_obj_t * TargetObject, int delay);
void eyeR_Animation(lv_obj_t * TargetObject, int delay);
void eyeL_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_clock;
extern lv_obj_t * ui_date;
void ui_event_logo(lv_event_t * e);
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_demo;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Container5;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_clock2;
extern lv_obj_t * ui_Container6;
void ui_event_Container7(lv_event_t * e);
extern lv_obj_t * ui_Container7;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_pm1label;
extern lv_obj_t * ui_Container8;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_PM3;
extern lv_obj_t * ui_PM1u2;
extern lv_obj_t * ui_PM1t2;
extern lv_obj_t * ui_pm25label;
extern lv_obj_t * ui_PM1;
extern lv_obj_t * ui_PM1u;
extern lv_obj_t * ui_PM1t;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_RHpercent;
extern lv_obj_t * ui_TVOC;
extern lv_obj_t * ui_TVOCppb;
void ui_event_Container9(lv_event_t * e);
extern lv_obj_t * ui_Container9;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_PM4;
extern lv_obj_t * ui_PM1u3;
extern lv_obj_t * ui_PM1t3;
extern lv_obj_t * ui_pm4label;
extern lv_obj_t * ui_Container10;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_PM2;
extern lv_obj_t * ui_PM1u4;
extern lv_obj_t * ui_PM1t4;
extern lv_obj_t * ui_pm10label;
void ui_event_Container11(lv_event_t * e);
extern lv_obj_t * ui_Container11;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_pm10label2;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_graphparameter;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_gpunit;
extern lv_obj_t * ui_gpvalue;
void ui_event_return(lv_event_t * e);
extern lv_obj_t * ui_return;
extern lv_obj_t * ui_returnlabel;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_graphparameter1;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_gpunit1;
extern lv_obj_t * ui_gpvalue1;
void ui_event_return1(lv_event_t * e);
extern lv_obj_t * ui_return1;
extern lv_obj_t * ui_returnlabel1;
// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_graphparameter2;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_gpunit2;
extern lv_obj_t * ui_gpvalue2;
void ui_event_return2(lv_event_t * e);
extern lv_obj_t * ui_return2;
extern lv_obj_t * ui_returnlabel2;
// SCREEN: ui_Screen7
void ui_Screen7_screen_init(void);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Chart4;
extern lv_obj_t * ui_graphparameter3;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_gpunit3;
extern lv_obj_t * ui_gpvalue3;
void ui_event_return3(lv_event_t * e);
extern lv_obj_t * ui_return3;
extern lv_obj_t * ui_returnlabel3;
// SCREEN: ui_Screen8
void ui_Screen8_screen_init(void);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Chart5;
extern lv_obj_t * ui_graphparameter4;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_gpunit4;
extern lv_obj_t * ui_gpvalue4;
void ui_event_return4(lv_event_t * e);
extern lv_obj_t * ui_return4;
extern lv_obj_t * ui_returnlabel4;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_sls_logo_png);    // assets/sls_logo.png



LV_FONT_DECLARE(ui_font_clock_66);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
